// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/command.proto

package tmp

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	// Types that are valid to be assigned to Command:
	//	*Command_TickCommand
	//	*Command_IdCommand
	//	*Command_WriterCommand
	Command              isCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type isCommand_Command interface {
	isCommand_Command()
}

type Command_TickCommand struct {
	TickCommand *TickCommand `protobuf:"bytes,2,opt,name=tick_command,json=tickCommand,proto3,oneof"`
}

type Command_IdCommand struct {
	IdCommand *IdCommand `protobuf:"bytes,3,opt,name=id_command,json=idCommand,proto3,oneof"`
}

type Command_WriterCommand struct {
	WriterCommand *WriterCommand `protobuf:"bytes,4,opt,name=writer_command,json=writerCommand,proto3,oneof"`
}

func (*Command_TickCommand) isCommand_Command() {}

func (*Command_IdCommand) isCommand_Command() {}

func (*Command_WriterCommand) isCommand_Command() {}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Command) GetTickCommand() *TickCommand {
	if x, ok := m.GetCommand().(*Command_TickCommand); ok {
		return x.TickCommand
	}
	return nil
}

func (m *Command) GetIdCommand() *IdCommand {
	if x, ok := m.GetCommand().(*Command_IdCommand); ok {
		return x.IdCommand
	}
	return nil
}

func (m *Command) GetWriterCommand() *WriterCommand {
	if x, ok := m.GetCommand().(*Command_WriterCommand); ok {
		return x.WriterCommand
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_TickCommand)(nil),
		(*Command_IdCommand)(nil),
		(*Command_WriterCommand)(nil),
	}
}

type TickCommand struct {
	RandomSeed           []byte   `protobuf:"bytes,1,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickCommand) Reset()         { *m = TickCommand{} }
func (m *TickCommand) String() string { return proto.CompactTextString(m) }
func (*TickCommand) ProtoMessage()    {}
func (*TickCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{1}
}

func (m *TickCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickCommand.Unmarshal(m, b)
}
func (m *TickCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickCommand.Marshal(b, m, deterministic)
}
func (m *TickCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickCommand.Merge(m, src)
}
func (m *TickCommand) XXX_Size() int {
	return xxx_messageInfo_TickCommand.Size(m)
}
func (m *TickCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TickCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TickCommand proto.InternalMessageInfo

func (m *TickCommand) GetRandomSeed() []byte {
	if m != nil {
		return m.RandomSeed
	}
	return nil
}

type IdCommand struct {
	OldId                string   `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NewId                string   `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdCommand) Reset()         { *m = IdCommand{} }
func (m *IdCommand) String() string { return proto.CompactTextString(m) }
func (*IdCommand) ProtoMessage()    {}
func (*IdCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{2}
}

func (m *IdCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdCommand.Unmarshal(m, b)
}
func (m *IdCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdCommand.Marshal(b, m, deterministic)
}
func (m *IdCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdCommand.Merge(m, src)
}
func (m *IdCommand) XXX_Size() int {
	return xxx_messageInfo_IdCommand.Size(m)
}
func (m *IdCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_IdCommand.DiscardUnknown(m)
}

var xxx_messageInfo_IdCommand proto.InternalMessageInfo

func (m *IdCommand) GetOldId() string {
	if m != nil {
		return m.OldId
	}
	return ""
}

func (m *IdCommand) GetNewId() string {
	if m != nil {
		return m.NewId
	}
	return ""
}

type WriterCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command              []byte   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriterCommand) Reset()         { *m = WriterCommand{} }
func (m *WriterCommand) String() string { return proto.CompactTextString(m) }
func (*WriterCommand) ProtoMessage()    {}
func (*WriterCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{3}
}

func (m *WriterCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriterCommand.Unmarshal(m, b)
}
func (m *WriterCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriterCommand.Marshal(b, m, deterministic)
}
func (m *WriterCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterCommand.Merge(m, src)
}
func (m *WriterCommand) XXX_Size() int {
	return xxx_messageInfo_WriterCommand.Size(m)
}
func (m *WriterCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterCommand.DiscardUnknown(m)
}

var xxx_messageInfo_WriterCommand proto.InternalMessageInfo

func (m *WriterCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WriterCommand) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type CreateRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{4}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

type CreateRoomResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{5}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

type AddWriterRequest struct {
	ProposedIds          []string `protobuf:"bytes,1,rep,name=proposed_ids,json=proposedIds,proto3" json:"proposed_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWriterRequest) Reset()         { *m = AddWriterRequest{} }
func (m *AddWriterRequest) String() string { return proto.CompactTextString(m) }
func (*AddWriterRequest) ProtoMessage()    {}
func (*AddWriterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{6}
}

func (m *AddWriterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWriterRequest.Unmarshal(m, b)
}
func (m *AddWriterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWriterRequest.Marshal(b, m, deterministic)
}
func (m *AddWriterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWriterRequest.Merge(m, src)
}
func (m *AddWriterRequest) XXX_Size() int {
	return xxx_messageInfo_AddWriterRequest.Size(m)
}
func (m *AddWriterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWriterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWriterRequest proto.InternalMessageInfo

func (m *AddWriterRequest) GetProposedIds() []string {
	if m != nil {
		return m.ProposedIds
	}
	return nil
}

type AddWriterResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWriterResponse) Reset()         { *m = AddWriterResponse{} }
func (m *AddWriterResponse) String() string { return proto.CompactTextString(m) }
func (*AddWriterResponse) ProtoMessage()    {}
func (*AddWriterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{7}
}

func (m *AddWriterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWriterResponse.Unmarshal(m, b)
}
func (m *AddWriterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWriterResponse.Marshal(b, m, deterministic)
}
func (m *AddWriterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWriterResponse.Merge(m, src)
}
func (m *AddWriterResponse) XXX_Size() int {
	return xxx_messageInfo_AddWriterResponse.Size(m)
}
func (m *AddWriterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWriterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWriterResponse proto.InternalMessageInfo

func (m *AddWriterResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DebugRequest struct {
	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are valid to be assigned to Oo:
	//	*DebugRequest_Oi32
	//	*DebugRequest_Oi64
	Oo                   isDebugRequest_Oo `protobuf_oneof:"oo"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DebugRequest) Reset()         { *m = DebugRequest{} }
func (m *DebugRequest) String() string { return proto.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()    {}
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{8}
}

func (m *DebugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRequest.Unmarshal(m, b)
}
func (m *DebugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRequest.Marshal(b, m, deterministic)
}
func (m *DebugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRequest.Merge(m, src)
}
func (m *DebugRequest) XXX_Size() int {
	return xxx_messageInfo_DebugRequest.Size(m)
}
func (m *DebugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRequest proto.InternalMessageInfo

func (m *DebugRequest) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *DebugRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *DebugRequest) GetI32() uint32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *DebugRequest) GetI64() uint64 {
	if m != nil {
		return m.I64
	}
	return 0
}

type isDebugRequest_Oo interface {
	isDebugRequest_Oo()
}

type DebugRequest_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugRequest_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugRequest_Oi32) isDebugRequest_Oo() {}

func (*DebugRequest_Oi64) isDebugRequest_Oo() {}

func (m *DebugRequest) GetOo() isDebugRequest_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (m *DebugRequest) GetOi32() uint32 {
	if x, ok := m.GetOo().(*DebugRequest_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (m *DebugRequest) GetOi64() uint64 {
	if x, ok := m.GetOo().(*DebugRequest_Oi64); ok {
		return x.Oi64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DebugRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DebugRequest_Oi32)(nil),
		(*DebugRequest_Oi64)(nil),
	}
}

type DebugResponse struct {
	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are valid to be assigned to Oo:
	//	*DebugResponse_Oi32
	//	*DebugResponse_Oi64
	Oo                   isDebugResponse_Oo `protobuf_oneof:"oo"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DebugResponse) Reset()         { *m = DebugResponse{} }
func (m *DebugResponse) String() string { return proto.CompactTextString(m) }
func (*DebugResponse) ProtoMessage()    {}
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{9}
}

func (m *DebugResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugResponse.Unmarshal(m, b)
}
func (m *DebugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugResponse.Marshal(b, m, deterministic)
}
func (m *DebugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugResponse.Merge(m, src)
}
func (m *DebugResponse) XXX_Size() int {
	return xxx_messageInfo_DebugResponse.Size(m)
}
func (m *DebugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebugResponse proto.InternalMessageInfo

func (m *DebugResponse) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *DebugResponse) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *DebugResponse) GetI32() uint32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *DebugResponse) GetI64() uint64 {
	if m != nil {
		return m.I64
	}
	return 0
}

type isDebugResponse_Oo interface {
	isDebugResponse_Oo()
}

type DebugResponse_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugResponse_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugResponse_Oi32) isDebugResponse_Oo() {}

func (*DebugResponse_Oi64) isDebugResponse_Oo() {}

func (m *DebugResponse) GetOo() isDebugResponse_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (m *DebugResponse) GetOi32() uint32 {
	if x, ok := m.GetOo().(*DebugResponse_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (m *DebugResponse) GetOi64() uint64 {
	if x, ok := m.GetOo().(*DebugResponse_Oi64); ok {
		return x.Oi64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DebugResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DebugResponse_Oi32)(nil),
		(*DebugResponse_Oi64)(nil),
	}
}

type RoomSetting struct {
	TickSetting          *TickSetting `protobuf:"bytes,1,opt,name=tick_setting,json=tickSetting,proto3" json:"tick_setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoomSetting) Reset()         { *m = RoomSetting{} }
func (m *RoomSetting) String() string { return proto.CompactTextString(m) }
func (*RoomSetting) ProtoMessage()    {}
func (*RoomSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{10}
}

func (m *RoomSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSetting.Unmarshal(m, b)
}
func (m *RoomSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSetting.Marshal(b, m, deterministic)
}
func (m *RoomSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSetting.Merge(m, src)
}
func (m *RoomSetting) XXX_Size() int {
	return xxx_messageInfo_RoomSetting.Size(m)
}
func (m *RoomSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSetting.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSetting proto.InternalMessageInfo

func (m *RoomSetting) GetTickSetting() *TickSetting {
	if m != nil {
		return m.TickSetting
	}
	return nil
}

type TickSetting struct {
	// number of bytes
	Size                 uint32   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	FrequencyMillis      uint32   `protobuf:"varint,2,opt,name=frequency_millis,json=frequencyMillis,proto3" json:"frequency_millis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickSetting) Reset()         { *m = TickSetting{} }
func (m *TickSetting) String() string { return proto.CompactTextString(m) }
func (*TickSetting) ProtoMessage()    {}
func (*TickSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{11}
}

func (m *TickSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickSetting.Unmarshal(m, b)
}
func (m *TickSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickSetting.Marshal(b, m, deterministic)
}
func (m *TickSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickSetting.Merge(m, src)
}
func (m *TickSetting) XXX_Size() int {
	return xxx_messageInfo_TickSetting.Size(m)
}
func (m *TickSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_TickSetting.DiscardUnknown(m)
}

var xxx_messageInfo_TickSetting proto.InternalMessageInfo

func (m *TickSetting) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TickSetting) GetFrequencyMillis() uint32 {
	if m != nil {
		return m.FrequencyMillis
	}
	return 0
}

func init() {
	proto.RegisterType((*Command)(nil), "tmp.Command")
	proto.RegisterType((*TickCommand)(nil), "tmp.TickCommand")
	proto.RegisterType((*IdCommand)(nil), "tmp.IdCommand")
	proto.RegisterType((*WriterCommand)(nil), "tmp.WriterCommand")
	proto.RegisterType((*CreateRoomRequest)(nil), "tmp.CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "tmp.CreateRoomResponse")
	proto.RegisterType((*AddWriterRequest)(nil), "tmp.AddWriterRequest")
	proto.RegisterType((*AddWriterResponse)(nil), "tmp.AddWriterResponse")
	proto.RegisterType((*DebugRequest)(nil), "tmp.DebugRequest")
	proto.RegisterType((*DebugResponse)(nil), "tmp.DebugResponse")
	proto.RegisterType((*RoomSetting)(nil), "tmp.RoomSetting")
	proto.RegisterType((*TickSetting)(nil), "tmp.TickSetting")
}

func init() { proto.RegisterFile("protobuf/command.proto", fileDescriptor_6997e64cf7b5f9bb) }

var fileDescriptor_6997e64cf7b5f9bb = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0x87, 0xeb, 0x36, 0xeb, 0x94, 0x37, 0x49, 0xe9, 0xcc, 0x36, 0x45, 0x5c, 0x28, 0xe1, 0x52,
	0x2e, 0x9d, 0xd4, 0x76, 0x95, 0x10, 0x5c, 0xe8, 0x38, 0xac, 0x02, 0x2e, 0x1e, 0x12, 0xc7, 0xaa,
	0x89, 0xbd, 0xc9, 0x5a, 0x13, 0x87, 0xd8, 0xa5, 0x82, 0x13, 0x7c, 0x2c, 0xbe, 0x1d, 0xf2, 0x9f,
	0xa4, 0xa1, 0x1f, 0x60, 0x37, 0xbf, 0x4f, 0xdf, 0xc7, 0xfd, 0xd9, 0x7e, 0x03, 0x97, 0x65, 0x25,
	0x94, 0x48, 0x77, 0xf7, 0x57, 0x99, 0xc8, 0xf3, 0x4d, 0x41, 0x27, 0x06, 0xe0, 0x9e, 0xca, 0xcb,
	0xe4, 0x2f, 0x82, 0xd3, 0x1b, 0x8b, 0xf1, 0x35, 0x84, 0x8a, 0x67, 0x8f, 0x6b, 0xd7, 0x16, 0x77,
	0x47, 0x68, 0x1c, 0x4c, 0x87, 0x13, 0x95, 0x97, 0x93, 0xaf, 0x3c, 0x7b, 0x74, 0x7d, 0xb7, 0x1d,
	0x12, 0xa8, 0x43, 0x89, 0xaf, 0x00, 0x38, 0x6d, 0xa4, 0x9e, 0x91, 0x06, 0x46, 0x5a, 0xd1, 0x83,
	0xe2, 0xf3, 0xba, 0xc0, 0xef, 0x60, 0xb0, 0xaf, 0xb8, 0x62, 0x55, 0x23, 0x79, 0x46, 0xc2, 0x46,
	0xfa, 0x66, 0x7e, 0x3a, 0x88, 0xd1, 0xbe, 0x0d, 0x96, 0x3e, 0x9c, 0x3a, 0x2b, 0x99, 0x40, 0xd0,
	0x8a, 0x85, 0x5f, 0x42, 0x50, 0x6d, 0x0a, 0x2a, 0xf2, 0xb5, 0x64, 0x8c, 0xc6, 0x68, 0x84, 0xc6,
	0x21, 0x01, 0x8b, 0xee, 0x18, 0xa3, 0xc9, 0x5b, 0xf0, 0x9b, 0x44, 0xf8, 0x02, 0xfa, 0x62, 0x4b,
	0xd7, 0xdc, 0x36, 0xfa, 0xe4, 0x44, 0x6c, 0xe9, 0xca, 0xe0, 0x82, 0xed, 0x35, 0xee, 0x5a, 0x5c,
	0xb0, 0xfd, 0x4a, 0xab, 0xd1, 0x7f, 0xb9, 0xf0, 0x00, 0xba, 0x8d, 0xda, 0xe5, 0x14, 0xc7, 0x4d,
	0x2c, 0x23, 0x86, 0xa4, 0x49, 0xf9, 0x1c, 0xce, 0x6e, 0x2a, 0xb6, 0x51, 0x8c, 0x08, 0x91, 0x13,
	0xf6, 0x7d, 0xc7, 0xa4, 0x4a, 0xce, 0x01, 0xb7, 0xa1, 0x2c, 0x45, 0x21, 0x59, 0x72, 0x0d, 0xc3,
	0x0f, 0x94, 0xda, 0x3f, 0x72, 0x9d, 0xf8, 0x15, 0x84, 0x65, 0x25, 0x4a, 0x21, 0x99, 0x0e, 0x2b,
	0x63, 0x34, 0xea, 0x8d, 0x7d, 0x12, 0xd4, 0x6c, 0x45, 0x65, 0xf2, 0x1a, 0xce, 0x5a, 0x9a, 0xdd,
	0xeb, 0x38, 0x60, 0xf2, 0x1b, 0x41, 0xf8, 0x91, 0xa5, 0xbb, 0x87, 0x7a, 0xe3, 0x10, 0x50, 0xea,
	0x2e, 0x09, 0xa5, 0xba, 0x92, 0xee, 0xc8, 0x48, 0xe2, 0x21, 0xf4, 0xf8, 0x6c, 0x6a, 0xde, 0x32,
	0x22, 0x7a, 0x69, 0xc8, 0x62, 0x6e, 0x1e, 0xca, 0x23, 0x7a, 0x89, 0xcf, 0xc1, 0x13, 0xba, 0xe9,
	0x44, 0x37, 0xdd, 0x76, 0x88, 0xa9, 0x2c, 0x5d, 0xcc, 0xe3, 0xbe, 0x6e, 0xb4, 0x74, 0x31, 0x5f,
	0x7a, 0xd0, 0x15, 0x22, 0xf9, 0x83, 0x20, 0x72, 0x11, 0x5c, 0xc8, 0xa7, 0xcf, 0xb0, 0x84, 0x40,
	0x5f, 0xf9, 0x1d, 0x53, 0x8a, 0x17, 0x0f, 0x78, 0xe6, 0x46, 0x5e, 0xda, 0xda, 0x64, 0x69, 0x8f,
	0xbc, 0xeb, 0xb3, 0x03, 0xef, 0x8a, 0xe4, 0xb3, 0x9d, 0xbb, 0x7a, 0x0f, 0x0c, 0x9e, 0xe4, 0xbf,
	0x98, 0x71, 0x23, 0x62, 0xd6, 0xf8, 0x0d, 0x0c, 0xef, 0x2b, 0x7d, 0xd1, 0x45, 0xf6, 0x73, 0x9d,
	0xf3, 0xed, 0x96, 0xdb, 0x93, 0x45, 0xe4, 0x59, 0xc3, 0xbf, 0x18, 0x3c, 0xfd, 0x54, 0x27, 0xaa,
	0x7e, 0xf0, 0x8c, 0xe1, 0xf7, 0xe0, 0x37, 0x8f, 0x89, 0x2f, 0x4c, 0x90, 0xe3, 0x99, 0x78, 0x71,
	0x79, 0x8c, 0xdd, 0xfc, 0x74, 0xd2, 0xbe, 0xf9, 0xb4, 0x67, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x5b, 0x90, 0x2d, 0x17, 0xf4, 0x03, 0x00, 0x00,
}
