// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/command.proto

package tmp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	// Types that are valid to be assigned to Command:
	//	*Command_RandomCommand
	//	*Command_IdCommand
	//	*Command_WriterCommand
	Command              isCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type isCommand_Command interface {
	isCommand_Command()
}

type Command_RandomCommand struct {
	RandomCommand *RandomCommand `protobuf:"bytes,2,opt,name=random_command,json=randomCommand,proto3,oneof"`
}

type Command_IdCommand struct {
	IdCommand *IdCommand `protobuf:"bytes,3,opt,name=id_command,json=idCommand,proto3,oneof"`
}

type Command_WriterCommand struct {
	WriterCommand *WriterCommand `protobuf:"bytes,4,opt,name=writer_command,json=writerCommand,proto3,oneof"`
}

func (*Command_RandomCommand) isCommand_Command() {}

func (*Command_IdCommand) isCommand_Command() {}

func (*Command_WriterCommand) isCommand_Command() {}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Command) GetRandomCommand() *RandomCommand {
	if x, ok := m.GetCommand().(*Command_RandomCommand); ok {
		return x.RandomCommand
	}
	return nil
}

func (m *Command) GetIdCommand() *IdCommand {
	if x, ok := m.GetCommand().(*Command_IdCommand); ok {
		return x.IdCommand
	}
	return nil
}

func (m *Command) GetWriterCommand() *WriterCommand {
	if x, ok := m.GetCommand().(*Command_WriterCommand); ok {
		return x.WriterCommand
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_RandomCommand)(nil),
		(*Command_IdCommand)(nil),
		(*Command_WriterCommand)(nil),
	}
}

type RandomCommand struct {
	Seed                 []byte   `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomCommand) Reset()         { *m = RandomCommand{} }
func (m *RandomCommand) String() string { return proto.CompactTextString(m) }
func (*RandomCommand) ProtoMessage()    {}
func (*RandomCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{1}
}

func (m *RandomCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomCommand.Unmarshal(m, b)
}
func (m *RandomCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomCommand.Marshal(b, m, deterministic)
}
func (m *RandomCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomCommand.Merge(m, src)
}
func (m *RandomCommand) XXX_Size() int {
	return xxx_messageInfo_RandomCommand.Size(m)
}
func (m *RandomCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RandomCommand proto.InternalMessageInfo

func (m *RandomCommand) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type IdCommand struct {
	OldId                string   `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NewId                string   `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdCommand) Reset()         { *m = IdCommand{} }
func (m *IdCommand) String() string { return proto.CompactTextString(m) }
func (*IdCommand) ProtoMessage()    {}
func (*IdCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{2}
}

func (m *IdCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdCommand.Unmarshal(m, b)
}
func (m *IdCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdCommand.Marshal(b, m, deterministic)
}
func (m *IdCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdCommand.Merge(m, src)
}
func (m *IdCommand) XXX_Size() int {
	return xxx_messageInfo_IdCommand.Size(m)
}
func (m *IdCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_IdCommand.DiscardUnknown(m)
}

var xxx_messageInfo_IdCommand proto.InternalMessageInfo

func (m *IdCommand) GetOldId() string {
	if m != nil {
		return m.OldId
	}
	return ""
}

func (m *IdCommand) GetNewId() string {
	if m != nil {
		return m.NewId
	}
	return ""
}

type WriterCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command              []byte   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriterCommand) Reset()         { *m = WriterCommand{} }
func (m *WriterCommand) String() string { return proto.CompactTextString(m) }
func (*WriterCommand) ProtoMessage()    {}
func (*WriterCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{3}
}

func (m *WriterCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriterCommand.Unmarshal(m, b)
}
func (m *WriterCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriterCommand.Marshal(b, m, deterministic)
}
func (m *WriterCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterCommand.Merge(m, src)
}
func (m *WriterCommand) XXX_Size() int {
	return xxx_messageInfo_WriterCommand.Size(m)
}
func (m *WriterCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterCommand.DiscardUnknown(m)
}

var xxx_messageInfo_WriterCommand proto.InternalMessageInfo

func (m *WriterCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WriterCommand) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type DebugRequest struct {
	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are valid to be assigned to Oo:
	//	*DebugRequest_Oi32
	//	*DebugRequest_Oi64
	Oo                   isDebugRequest_Oo `protobuf_oneof:"oo"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DebugRequest) Reset()         { *m = DebugRequest{} }
func (m *DebugRequest) String() string { return proto.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()    {}
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{4}
}

func (m *DebugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRequest.Unmarshal(m, b)
}
func (m *DebugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRequest.Marshal(b, m, deterministic)
}
func (m *DebugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRequest.Merge(m, src)
}
func (m *DebugRequest) XXX_Size() int {
	return xxx_messageInfo_DebugRequest.Size(m)
}
func (m *DebugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRequest proto.InternalMessageInfo

func (m *DebugRequest) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *DebugRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *DebugRequest) GetI32() uint32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *DebugRequest) GetI64() uint64 {
	if m != nil {
		return m.I64
	}
	return 0
}

type isDebugRequest_Oo interface {
	isDebugRequest_Oo()
}

type DebugRequest_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugRequest_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugRequest_Oi32) isDebugRequest_Oo() {}

func (*DebugRequest_Oi64) isDebugRequest_Oo() {}

func (m *DebugRequest) GetOo() isDebugRequest_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (m *DebugRequest) GetOi32() uint32 {
	if x, ok := m.GetOo().(*DebugRequest_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (m *DebugRequest) GetOi64() uint64 {
	if x, ok := m.GetOo().(*DebugRequest_Oi64); ok {
		return x.Oi64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DebugRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DebugRequest_Oi32)(nil),
		(*DebugRequest_Oi64)(nil),
	}
}

type DebugResponse struct {
	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are valid to be assigned to Oo:
	//	*DebugResponse_Oi32
	//	*DebugResponse_Oi64
	Oo                   isDebugResponse_Oo `protobuf_oneof:"oo"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DebugResponse) Reset()         { *m = DebugResponse{} }
func (m *DebugResponse) String() string { return proto.CompactTextString(m) }
func (*DebugResponse) ProtoMessage()    {}
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6997e64cf7b5f9bb, []int{5}
}

func (m *DebugResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugResponse.Unmarshal(m, b)
}
func (m *DebugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugResponse.Marshal(b, m, deterministic)
}
func (m *DebugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugResponse.Merge(m, src)
}
func (m *DebugResponse) XXX_Size() int {
	return xxx_messageInfo_DebugResponse.Size(m)
}
func (m *DebugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebugResponse proto.InternalMessageInfo

func (m *DebugResponse) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *DebugResponse) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *DebugResponse) GetI32() uint32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *DebugResponse) GetI64() uint64 {
	if m != nil {
		return m.I64
	}
	return 0
}

type isDebugResponse_Oo interface {
	isDebugResponse_Oo()
}

type DebugResponse_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugResponse_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugResponse_Oi32) isDebugResponse_Oo() {}

func (*DebugResponse_Oi64) isDebugResponse_Oo() {}

func (m *DebugResponse) GetOo() isDebugResponse_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (m *DebugResponse) GetOi32() uint32 {
	if x, ok := m.GetOo().(*DebugResponse_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (m *DebugResponse) GetOi64() uint64 {
	if x, ok := m.GetOo().(*DebugResponse_Oi64); ok {
		return x.Oi64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DebugResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DebugResponse_Oi32)(nil),
		(*DebugResponse_Oi64)(nil),
	}
}

func init() {
	proto.RegisterType((*Command)(nil), "tmp.Command")
	proto.RegisterType((*RandomCommand)(nil), "tmp.RandomCommand")
	proto.RegisterType((*IdCommand)(nil), "tmp.IdCommand")
	proto.RegisterType((*WriterCommand)(nil), "tmp.WriterCommand")
	proto.RegisterType((*DebugRequest)(nil), "tmp.DebugRequest")
	proto.RegisterType((*DebugResponse)(nil), "tmp.DebugResponse")
}

func init() { proto.RegisterFile("protobuf/command.proto", fileDescriptor_6997e64cf7b5f9bb) }

var fileDescriptor_6997e64cf7b5f9bb = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x86, 0xd9, 0x52, 0x20, 0x1d, 0x5a, 0xf2, 0x7d, 0x13, 0x35, 0x8d, 0x27, 0x52, 0x2f, 0x9c,
	0xc0, 0x00, 0x21, 0x31, 0x1e, 0x4c, 0xd0, 0x03, 0x5c, 0xd7, 0x83, 0x47, 0x42, 0xd9, 0xd5, 0x6c,
	0x42, 0xbb, 0xb5, 0x2d, 0xf6, 0xaa, 0xbf, 0xcc, 0xbf, 0x66, 0x76, 0xda, 0xd4, 0xe5, 0x0f, 0x78,
	0xdb, 0x7d, 0xf6, 0x7d, 0x33, 0x4f, 0xa6, 0x85, 0xab, 0x2c, 0xd7, 0xa5, 0x8e, 0x4f, 0xaf, 0xb3,
	0x83, 0x4e, 0x92, 0x7d, 0x2a, 0xa6, 0x04, 0xb0, 0x5b, 0x26, 0x59, 0xf4, 0xcd, 0x60, 0xf0, 0x58,
	0x63, 0xbc, 0x87, 0x51, 0xbe, 0x4f, 0x85, 0x4e, 0x76, 0x4d, 0x30, 0x74, 0xc6, 0x6c, 0x32, 0x9c,
	0xe3, 0xb4, 0x4c, 0xb2, 0x29, 0xa7, 0xa7, 0x26, 0xbb, 0xe9, 0xf0, 0x20, 0xb7, 0x01, 0xce, 0x00,
	0x94, 0x68, 0x8b, 0x5d, 0x2a, 0x8e, 0xa8, 0xb8, 0x15, 0xbf, 0x25, 0x4f, 0x09, 0x6b, 0x5a, 0x95,
	0xab, 0x52, 0xe6, 0x6d, 0xc9, 0xb5, 0xa6, 0xbd, 0xd0, 0x93, 0x35, 0xad, 0xb2, 0xc1, 0xda, 0x83,
	0x41, 0xd3, 0x8a, 0x6e, 0x20, 0x38, 0x53, 0x43, 0x04, 0xb7, 0x90, 0x52, 0x84, 0x6c, 0xcc, 0x26,
	0x3e, 0xa7, 0x73, 0x74, 0x07, 0x5e, 0xab, 0x81, 0x97, 0xd0, 0xd7, 0x47, 0xb1, 0x53, 0x75, 0xc4,
	0xe3, 0x3d, 0x7d, 0x14, 0x5b, 0xc2, 0xa9, 0xac, 0x0c, 0x76, 0x6a, 0x9c, 0xca, 0x6a, 0x6b, 0xaa,
	0xc1, 0x99, 0x0c, 0x8e, 0xc0, 0x69, 0xab, 0x8e, 0x12, 0x18, 0xb6, 0x2e, 0x54, 0xf4, 0x79, 0xab,
	0xf6, 0xc9, 0xc0, 0x7f, 0x92, 0xf1, 0xe9, 0x8d, 0xcb, 0xf7, 0x93, 0x2c, 0x4a, 0xf4, 0x81, 0xc5,
	0x8d, 0x17, 0x8b, 0xcd, 0xad, 0x68, 0x66, 0xb1, 0x02, 0xff, 0x41, 0x57, 0x2d, 0xe6, 0xb4, 0xb9,
	0x80, 0x9b, 0x23, 0x91, 0xd5, 0x92, 0xd6, 0xe2, 0x72, 0x73, 0xc4, 0x0b, 0x70, 0xb5, 0x09, 0xf5,
	0x4c, 0x68, 0xd3, 0xe1, 0x74, 0xab, 0xe9, 0x6a, 0x19, 0xf6, 0x4d, 0xb0, 0xa6, 0xab, 0xe5, 0xda,
	0x05, 0x47, 0xeb, 0xe8, 0x8b, 0x41, 0xd0, 0x28, 0x14, 0x99, 0x4e, 0x0b, 0xf9, 0xf7, 0x0e, 0xf3,
	0x07, 0x18, 0x72, 0xad, 0x93, 0x67, 0x99, 0x7f, 0xa8, 0x83, 0xc4, 0x5b, 0xe8, 0x09, 0x63, 0x84,
	0xff, 0xe9, 0x4b, 0xdb, 0x0b, 0xba, 0x46, 0x1b, 0xd5, 0xc2, 0x51, 0x27, 0xee, 0xd3, 0x0f, 0xbb,
	0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x10, 0xe1, 0x11, 0xfc, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error) {
	out := new(DebugResponse)
	err := c.cc.Invoke(ctx, "/tmp.RoomService/debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	Debug(context.Context, *DebugRequest) (*DebugResponse, error)
}

// UnimplementedRoomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomServiceServer struct {
}

func (*UnimplementedRoomServiceServer) Debug(ctx context.Context, req *DebugRequest) (*DebugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tmp.RoomService/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).Debug(ctx, req.(*DebugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tmp.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "debug",
			Handler:    _RoomService_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/command.proto",
}
